width=20;
 height=8;
 x0=1;
 y0=1;
figure('Units','inches',...
'Position',[x0 y0 width height],...
'PaperPositionMode','auto');
% (x0,y0) = position of the lower left side of the figure
t = 0:.1:4*pi;
y = sin(t);
plot(t,y)
xlabel('Time(s)')
ylabel('y(t)')
title('Sin function')
legend('y=sin(t)')

axis([0 t(end) -1.5 1.5]);
set(gca,...
'Units','normalized', 'YTick',-1.5:.5:1.5,...
'XTick', 0:t(end)/4:t(end),... 
'Position',[.15 .2 .75 .7],... 
'FontUnits','points',... 
'FontWeight','normal',... 
'FontSize',20,... 
'FontName','Times')


ylabel({'$y(t)$'},... 
          'FontUnits' , 'points',... 
          'interpreter' ,'latex',... 
          'FontSize',20,... 
          'FontName','Times')
xlabel('Time(s)',... 
         'FontUnits','points',... 
         'FontWeight','normal',... 
         'FontSize',20,... 
         'FontName','Times')
     
legend({'$y=\sin(t)$'},... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',20,... 
    'FontName','Times',... 
    'Location','NorthEast')
title('Sinusoidal function',... 
    'FontUnits','points',... 
    'FontWeight','normal',... 
    'FontSize',20,... 
    'FontName','Times')
print -depsc2 myplot.eps